version: '3'

services:
  db_busticket:
      image: "postgres"
      container_name: db_busticket
      ports:
        - "5433:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DATABASES: postgres
      volumes:
        - ./scripts:/docker-entrypoint-initdb.d